apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  # namespace: default
  # labels:
  #   app: db-pvc
spec:
  # storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi